name: Code Tests with Latest branca

on:
  pull_request:
  push:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Conda
      uses: s-weigand/setup-conda@v1
      with:
        activate-conda: false
        update-conda: true
        conda-channels: conda-forge

    - name: Python 3.x
      shell: bash -l {0}
      run: |
        conda create --yes --name TEST python=3 pip --file requirements.txt --file requirements-dev.txt
        source activate TEST
        pip install -e . --no-deps --force-reinstall

    - name: Tests with latest branca
      shell: bash -l {0}
      run: |
        source activate TEST
        conda remove branca --yes
        pip install git+https://github.com/python-visualization/branca.git
        pytest -vv --ignore=tests/selenium
