name: Code Tests with Latest branca

on:
  schedule:
    - cron: "0 13 * * *"
  pull_request:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Micromamba env
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-name: TEST
        create-args: >-
          python=3
          --file requirements.txt
          --file requirements-dev.txt

    - name: Install folium from source
      shell: bash -l {0}
      run: python -m pip install -e . --no-deps --force-reinstall

    - name: Tests with latest branca
      shell: bash -l {0}
      run: |
        micromamba remove branca --yes --force
        python -m pip install git+https://github.com/python-visualization/branca.git
        coverage run -p -m pytest -vv --ignore=tests/selenium --ignore=tests/playwright --ignore=tests/snapshots

    - name: Upload coverage
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-test-branca
        path: |
          .coverage*
